sudo update-alternatives --config jar
sudo update-alternatives --config jarsigner
sudo update-alternatives --config java
sudo update-alternatives --config javac
sudo update-alternatives --config javadoc
sudo update-alternatives --config javah
sudo update-alternatives --config javaws
sudo update-alternatives --config javap


sudo update-alternatives --config appletviewer
sudo update-alternatives --config extcheck 
sudo update-alternatives --config idlj 
sudo update-alternatives --config jconsole 
sudo update-alternatives --config jdb 
sudo update-alternatives --config jhat 
sudo update-alternatives --config jmap
sudo update-alternatives --config jps 
sudo update-alternatives --config jrunscript
sudo update-alternatives --config jsadebugd 
sudo update-alternatives --config jstack 
sudo update-alternatives --config jstat 
sudo update-alternatives --config jstatd 
sudo update-alternatives --config keytool 
sudo update-alternatives --config native2ascii 
sudo update-alternatives --config orbd 
sudo update-alternatives --config pack200 
sudo update-alternatives --config policytool 
sudo update-alternatives --config rmic 
sudo update-alternatives --config rmid 
sudo update-alternatives --config rmiregistry 
sudo update-alternatives --config schemagen 
sudo update-alternatives --config serialver 
sudo update-alternatives --config servertool 
sudo update-alternatives --config tnameserv 
sudo update-alternatives --config unpack200 
sudo update-alternatives --config wsgen 
sudo update-alternatives --config wsimport 
sudo update-alternatives --config xjc 
